#!/bin/bash
# author:tracyone
# date:2013-09-01/11:16:06
# description:此脚本实现vmware下的ubuntu的完整备份.
#			1,恢复时必须另外新建一个虚拟机
#			2,恢复时必须先建立两个分区一个主分区用于存放/,剩下空间作为扩展空间，扩展空间全部作为swap分区
#				所以分区好之后，在dev文件下应该存在sda1和sda5
#			3,请进入live cd下进行以下操作

#备份的文件..
FULLBACKUP="full_$(date +%Y%m%d).tar.bz2"
#增量备份的文件...
DIFFBACKUP="diff_$(date +%Y%m%d).tar.bz2"
#增量备份文件信息文件
DIFFINFO=backup.shot
#备份文件存放地
BACKUPDIR=/mnt/backup
#个人不想包括的文件...
EXCLUDE=" --exclude=./root/at91samx5 --exclude=./root/vimwiki --exclude=./root/Project --exclude=./work --exclude=./root/targetfs "

# 检测参数.....
if [[ "$#" -ne 1 ]]; then
	echo -e "Usage:$0 backup|restore"
	exit 2
fi

# 你必须是root用户...
echo -e "You must root..."
sudo -s


# 开始备份或者恢复....
if [[ "$1" == "backup" ]]; then
	echo -e "mount /dev/sda1 to /mnt"
	mount /dev/sda1 /mnt
	if [[ "$?" -ne 0 ]]; then
		echo "mount /dev/sda1 faild..."
		exit 3
	fi
	# 读取用户输入..备份文件所要放的路径
	read -p "Please input the path that you want to store your backup file[/mnt/backup]" BACKUPDIR
	if [[ "$BACKUPDIR" == "" ]]; then
		BACKUPDIR=/mnt/backup
	fi

	# 检测BACKUPDIR是否存在，不存在就创建...
	if [[ ! -d "$BACKUPDIR" ]]; then
		echo -e "$BACKUPDIR is not exist,we create it.."
		mkdir -p $BACKUPDIR
		while [[ "$?" -ne 0 ]]; do
			echo -e "A invalid path or permission denied or Read only!\nTry another path!\n"
			read -p "Please input the path that you want to store your backup file[/mnt/backup]" BACKUPDIR
			if [[ "$BACKUPDIR" == "" ]]; then
				BACKUPDIR=/mnt/backup
			fi
			mkdir -p $BACKUPDIR
		done
	fi

	# ...好吧再检查下写权限是否具备...
	if [[ ! -w "$BACKUPDIR" ]]; then
		echo "unable to write"
		chmod a+w $BACKUPDIR
		if [[ "$?" -ne 0 ]]; then
			echo "Unable to add w to $BACKUPDIR\nwe exit...f"
			exit 4
		fi
	fi

	# 如果选择将备份文件保存在与被备份系统的相同分区内，
	# 则将其路径或者文件也加入排除行列
	if [[ "${BACKUPDIR:1:4}" == "mnt/" || "${BACKUPDIR:1:4}" == "mnt" ]]; then
		if [[ "$(expr length ${BACKUPDIR})" -gt 5 ]]; then
			EXCLUDE="$EXCLUDE --exclude=.${BACKUPDIR:4} "
		else
			EXCLUDE="$EXCLUDE --exclude=./$FULLBACKUP --exclude=./$DIFFBACKUP "
		fi
	else
		echo -e "...\n"
	fi
	# 检查完整备份的文件和增量备份信息的文件是否存在..
	cd $BACKUPDIR
	ls full_*.tar.bz2 > /dev/null 2>&1 && ls backup.shot > /dev/null 2>&1
	if [[ "$?" -ne 0 ]]; then
		cd /mnt
		echo -e "Start Full backup..."
		sudo tar -g ${BACKUPDIR}/${DIFFINFO} \
			-cvpjf ${BACKUPDIR}/${FULLBACKUP} --directory=/mnt \
			--exclude=./mnt \
			--exclude=./lost+found \
			--exclude=./media \
			--exclude=./tmp \
			--exclude=./sys \
			${EXCLUDE} .
		echo -e "$FULLBACKUP and $DIFFINFO was generated\n"
	else
		cd /mnt
		echo -e "Start increment backup..."
		sudo tar -g ${BACKUPDIR}/${DIFFINFO} \
			-cvpjf ${BACKUPDIR}/${DIFFBACKUP} --directory=/ \
			--exclude=./mnt \
			--exclude=./lost+found \
			--exclude=./media \
			--exclude=./tmp \
			--exclude=./sys \
			${EXCLUDE} .
		echo -e "$DIFFBACKUP and $DIFFINFO was generated\n"
	fi
	#获取/dev/sda1和/dev/sda5的uuid,保存在uuid_info文件里
	blkid -o value /dev/sda1 > uuid_info
	blkid -o value /dev/sda5 >> uuid_info
	echo -e "File uuid_info[important] was generated\n"
	echo "backup finish....$(date +%Y%m%d)"
	exit 0
elif [[ "$1" == "restore" ]]; then
	echo -e "change /dev/sda1 and /dev/sda5 uuid...."
	ls /dev/sda1 > /dev/null 2>&1 && ls /dev/sda5 > /dev/null 2>&1
	if [[ "$?" -ne 0 ]]; then
		echo "/dev/sda1 or /dev/sda5 is not exist"
		echo "Make sure you have partitioned appropriately"
		exit 5
	fi
	SDA1_UUID=$(cat uuid_info | sed -n '2p')
	SDA5_UUID=$(cat uuid_info | sed -n '5p')
	tune2fs -U $SDA1_UUID /dev/sda1
	mkswap -U $SDA5_UUID /dev/sda5
	echo -e "mount /dev/sda1 to /mnt"
	mount /dev/sda1 /mnt
	if [[ "$?" -ne 0 ]]; then
		echo "mount /dev/sda1 faild..."
		exit 3
	fi
	#---------------------------------------------------------------
	ls full_*.tar.bz2 > /dev/null 2>&1
	if [[ "$?" -ne 0 ]]; then
		echo "full backup file is not exist in current directory "
		exit 6
	else
		echo "start fullbackp restore...."
		for i in full_*.tar.bz2; do
			tar -xvjpf $i -C /mnt
		done
	fi
	ls diff_*.tar.bz2 > /dev/null 2>&1
	if [[ "$?" -ne 0 ]]; then
		echo "diff backup file is not exist in current directory "
	else
		echo "start increment restore...."
		for i in diff_*.tar.bz2; do
			tar -xvjpf $i -C /mnt
		done
	fi
	cd /mnt
	echo "creating some system directory"
	mkdir sys mnt media tmp 
	mkdir mnt/hgfs
	chmod 1777 tmp
	echo "install grub into /dev/sda"
	grub-install --root-directory=/mnt /dev/sda
	echo "Restoe finish------------------"
	exit 0
else
	echo -e "Usage:$0 backup|restore"
	exit 2
fi
