#!/bin/bash
#author:tracyone
#date:2015-05-15/18:01:15
#usage:
#gif-record [-r|-w] [seconds]
#gif-record #直接录制默认录制时间是10秒,默认是选定区域进行录制
#gif-record -w 20 #录制20秒,选择窗口进行录制
#gif-record  20 #录制20秒,选择区域进行录制
# xrectsel from https://github.com/lolilolicon/xrectsel

# Delay before starting
DELAY=5

source $(dirname $(which gif-record))/script_libs/common.sh

bell_file=$(locate Amsterdam.ogg)
# Sound notification to let one know when recording is about to start (and ends)
beep() {
	play ${bell_file} > /tmp/gif_record_tmp 2>&1  &
}

# echo_usage:
# argument:none
function echo_usage()
{
   echo -e "\nusage:gif-record [-r|-w] [seconds] [-h]\n"
   echo -e "-r,region,specify the region of gif.(default)\n"
   echo -e "-w,use current windows as the region of gif\n"
   echo -e "-h,show this help\n"
   echo -e "seconds:gif duration,( default is 10s )\n"
}

configure "sox byzanz-record xrectsel"

clear_screen

if [[ $1 == "-h" ]]; then
		echo_usage
		exit 0
fi

echo -e "\nPlease specify the region of gif!\n"

if [[ $LANGUAGE == "zh_CN:zh" ]]; then
	if [[ ! -d "${HOME}/图片/gif_record" ]]; then
		mkdir -p "${HOME}/图片/gif_record" 
	fi
	file_save="${HOME}/图片/gif_record/$(date +%y%m%d%s).gif"
else
	if [[ ! -d "${HOME}/Pictures/gif_record" ]]; then
		mkdir -p "${HOME}/Pictures/gif_record" 
	fi
	file_save="${HOME}/Pictures/gif_record/$(date +%y%m%d%s).gif"
fi


case $# in
	'0' )
		D="--duration=10 ${file_save}"
		# xrectsel from https://github.com/lolilolicon/FFcast2/blob/master/xrectsel.c
		ARGUMENTS=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1

		echo Delaying $DELAY seconds. After that, byzanz will start
		for (( i=$DELAY; i>0; --i )) ; do
			echo $i
			sleep 1
		done
		beep
		byzanz-record -c --verbose --delay=0 ${ARGUMENTS} $D
		beep
		xdg-open ${file_save} 2> /tmp/gif_record_tmp
		exit 0
		;;
	'1' )
		D="--duration=$1 ${file_save}"
		# xrectsel from https://github.com/lolilolicon/FFcast2/blob/master/xrectsel.c
		ARGUMENTS=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1

		echo Delaying $DELAY seconds. After that, byzanz will start
		for (( i=$DELAY; i>0; --i )) ; do
			echo $i
			sleep 1
		done
		beep
		byzanz-record -c --verbose --delay=0 ${ARGUMENTS} $D
		beep
		xdg-open ${file_save} 2> /tmp/gif_record_tmp
		exit 0
		;;
	'2' )
		D="--duration=$2 ${file_save}"
		;;
	* )
	echo "Usage:$0 [-r|-w] [seconds]"
	exit 1
		;;
esac

case $1 in
	'-r' )
		ARGUMENTS=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1

		echo Delaying $DELAY seconds. After that, byzanz will start
		for (( i=$DELAY; i>0; --i )) ; do
			echo $i
			sleep 1
		done
		beep
		byzanz-record -c --verbose --delay=0 ${ARGUMENTS} $D
		beep
		;;
	'-w' )
		XWININFO=$(xwininfo)
		read X < <(awk -F: '/Absolute upper-left X/{print $2}' <<< "$XWININFO")
		read Y < <(awk -F: '/Absolute upper-left Y/{print $2}' <<< "$XWININFO")
		read W < <(awk -F: '/Width/{print $2}' <<< "$XWININFO")
		read H < <(awk -F: '/Height/{print $2}' <<< "$XWININFO")

		echo Delaying $DELAY seconds. After that, byzanz will start
		for (( i=$DELAY; i>0; --i )) ; do
			echo $i
			sleep 1
		done
		beep
		byzanz-record -c --verbose --delay=0 --x=$X --y=$Y --width=$W --height=$H $D
		beep
		;;
	* )
		echo "Usage:$0 [-r|-w] [seconds]"
		exit 3
		;;
esac

echo "gif file is saved to ${file_save}"
xdg-open ${file_save} 2> /tmp/gif_record_tmp
rm /tmp/gif_record_tmp
