#!/bin/bash

# Delay before starting
DELAY=5

function configure()
{
	local package_lack=""
	for i in $1
	do
		which $i > /dev/null 2>&1
		if [[ $? -ne 0 ]]; then
			echo -e "Checking for $i ..... no"
			package_lack="$i ${package_lack}"
		fi
	done	
	if [[ ${package_lack} != "" ]]; then
		echo "Please install ${package_lack} manually!"
		exit 3
	fi
}

bell_file=$(locate bell.oga)
# Sound notification to let one know when recording is about to start (and ends)
beep() {
	play ${bell_file} > /tmp/gif_record_tmp 2>&1  &
}

configure "sox byzanz-record xrectsel"

if [[ $LANG == "zh_CN.UTF-8" ]]; then
	if [[ ! -d "${HOME}/图片/gif_record" ]]; then
		mkdir -p "${HOME}/图片/gif_record" 
	fi
	file_save="${HOME}/图片/gif_record"
else
	if [[ ! -d "${HOME}/Pictures/gif_record" ]]; then
		mkdir -p "${HOME}/Pictures/gif_record" 
	fi
	file_save="${HOME}/Pictures/gif_record"
fi

# Duration and output file
if [ $# -gt 0 ]; then
    D="--duration=$2 ${file_save}/$(date +%y%m%d%s).gif"
else
    D="--duration=10 ${file_save}/$(date +%y%m%d%s).gif"
	# xrectsel from https://github.com/lolilolicon/FFcast2/blob/master/xrectsel.c
	ARGUMENTS=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1

	echo Delaying $DELAY seconds. After that, byzanz will start
	for (( i=$DELAY; i>0; --i )) ; do
		echo $i
		sleep 1
	done
	beep
	byzanz-record --verbose --delay=0 ${ARGUMENTS} $D
	beep
	exit 0
fi

if [[ $# -gt 2 ]]; then
	echo "Usage:$0 -r|-w seconds"
	exit 3
else
	case $1 in
		'-r' )
			# xrectsel from https://github.com/lolilolicon/FFcast2/blob/master/xrectsel.c
			ARGUMENTS=$(xrectsel "--x=%x --y=%y --width=%w --height=%h") || exit -1

			echo Delaying $DELAY seconds. After that, byzanz will start
			for (( i=$DELAY; i>0; --i )) ; do
				echo $i
				sleep 1
			done
			beep
			byzanz-record --verbose --delay=0 ${ARGUMENTS} $D
			beep
			;;
		'-w' )
			XWININFO=$(xwininfo)
			read X < <(awk -F: '/Absolute upper-left X/{print $2}' <<< "$XWININFO")
			read Y < <(awk -F: '/Absolute upper-left Y/{print $2}' <<< "$XWININFO")
			read W < <(awk -F: '/Width/{print $2}' <<< "$XWININFO")
			read H < <(awk -F: '/Height/{print $2}' <<< "$XWININFO")

			echo Delaying $DELAY seconds. After that, byzanz will start
			for (( i=$DELAY; i>0; --i )) ; do
				echo $i
				sleep 1
			done
			beep
			byzanz-record --verbose --delay=0 --x=$X --y=$Y --width=$W --height=$H $D
			beep
			;;
		* )
			echo "Usage:$0 -r|-w seconds"
			exit 3
			;;
	esac
fi

echo "gif file is saved to ${file_save}/$(date +%y%m%d%s).gif"
rm /tmp/gif_record_tmp
